--1. TOTAL REVENUE

SELECT ROUND(SUM(TOTALPRICE),0) AS TOTAL_REVENUE
FROM ORDERS

--2. TOTAL ORDERS

SELECT COUNT(DISTINCT ID) AS TOTAL_ORDERS
FROM ORDERS

--3. AVERAGE ORDER VALUE

SELECT ROUND(AVG(TOTALPRICE),0) AS AVG_ORDER_VALUE
FROM ORDERS

--4. AVERAGE REVENUE PER CUSTOMER

SELECT (SUM(O.TOTALPRICE) / COUNT(DISTINCT O.USERID)) AS AVG_REVENUE_PER_CUSTOMER
FROM ORDERS O
