--1.REVENUE BY CITY

SELECT C.CITY, ROUND(SUM(O.TOTALPRICE),0) AS TOTAL_REVENUE FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY
ORDER BY TOTAL_REVENUE DESC

--2.TOP 10 CITIES BY REVENUE

SELECT TOP 10 C.CITY, ROUND(SUM(O.TOTALPRICE),0) AS TOTAL_REVENUE FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY
ORDER BY TOTAL_REVENUE DESC

--CITIES ABOVE AVERAGE SALES

SELECT C.CITY, ROUND(SUM(O.TOTALPRICE),0) AS SUM_REVENUE_BY_CITY
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY
HAVING SUM(O.TOTALPRICE) > 
	(
		SELECT AVG(T.SUM_REVENUE_BY_CITY) FROM 
		(
			SELECT C.CITY, ROUND(SUM(O.TOTALPRICE),0) AS SUM_REVENUE_BY_CITY
			FROM ORDERS O
			JOIN ADDRESS A ON A.ID=O.ADDRESSID
			JOIN CITIES C ON C.ID=A.CITYID
			GROUP BY C.CITY
		) AS T
	) 
ORDER BY 2 DESC

--4. CITY CONTRIBUTION %

SELECT C.CITY, ROUND(SUM(O.TOTALPRICE),0) AS TOTAL_REVENUE,
ROUND(100*SUM(O.TOTALPRICE)/(SELECT SUM(TOTALPRICE)FROM ORDERS ),2) CITY_CONTRIBUTION
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.CITY
ORDER BY 3 DESC
