--1.TOP CUSTOMERS BY REVENUE

SELECT TOP 1  U.ID, U.NAMESURNAME, 
SUM(O.TOTALPRICE) AS TOTAL_REVENUE FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 3 DESC

--2.TOP 10 CUSTOMERS BY REVENUE

SELECT TOP 10  U.ID, U.NAMESURNAME, 
SUM(O.TOTALPRICE) AS TOTAL_REVENUE FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 3 DESC

--3.AVERAGE REVENUE PER CUSTOMER

SELECT AVG(CUSTOMER_REVENUE) AS AVG_REVENUE_PER_CUSTOMER
FROM
(
	SELECT 
	O.USERID,
	SUM(O.TOTALPRICE) AS CUSTOMER_REVENUE
	FROM ORDERS O
	GROUP BY O.USERID
) AS CUSTOMERTOTALS

--4.AVERAGE ORDER REVENUE BY CUSTOMER

SELECT  U.ID, U.NAMESURNAME, 
AVG(O.TOTALPRICE) AS AVG_REVENUE FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 1 

--5. CUSTOMER ABOVE AVERAGE SPENDING

SELECT  U.ID, U.NAMESURNAME, 
SUM(O.TOTALPRICE) AS SUM_REVENUE FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
HAVING SUM(O.TOTALPRICE) >  
( 
	SELECT AVG(T.SUM_REVENUE) FROM
	(
		SELECT  U.ID, U.NAMESURNAME, 
		SUM(O.TOTALPRICE) AS SUM_REVENUE FROM ORDERS O
		JOIN USERS U ON U.ID=O.USERID
		GROUP BY U.ID, U.NAMESURNAME
	) AS T
)
ORDER BY 3 DESC 


--6.CUSTOMER CONTRIBUTION %
SELECT  U.ID, U.NAMESURNAME, 
ROUND(SUM(O.TOTALPRICE),0) AS SUM_REVENUE, 
ROUND(100*SUM(O.TOTALPRICE)/(SELECT SUM(TOTALPRICE) FROM ORDERS),2) AS CUSTOMER_CONTRIBUTION
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 4 DESC 

--7. REPEAT CUSTOMERS

SELECT U.ID, U.NAMESURNAME, COUNT( DISTINCT O.ID) AS ORDER_COUNT,
SUM(O.TOTALPRICE) AS TOTAL_REVENUE FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
HAVING COUNT( DISTINCT O.ID) > 1
ORDER BY 3 DESC,4 DESC

--8.ORDER FREQUENCY BY CUSTOMER 
SELECT U.ID, U.NAMESURNAME, 
COUNT( DISTINCT O.ID) AS ORDER_COUNT,
SUM(O.TOTALPRICE) AS TOTAL_REVENUE, 
AVG(O.TOTALPRICE) AS AVG_REVENUE 
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
GROUP BY U.ID, U.NAMESURNAME
ORDER BY 3 DESC,4 DESC
