--1.MONTHLY SALES TREND

SELECT 
  YEAR(O.DATE_) AS ORDER_YEAR,
  MONTH(O.DATE_) AS ORDER_MONTH,
  ROUND(SUM(O.TOTALPRICE),0) AS TOTAL_PRICE
FROM ORDERS O
GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
ORDER BY 1,2

--2.MONTHLY ORDER COUNT

SELECT 
  YEAR(O.DATE_) AS ORDER_YEAR,
  MONTH(O.DATE_) AS ORDER_MONTH,
  COUNT(DISTINCT O.ID) AS ORDER_COUNT
FROM ORDERS O
GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
ORDER BY 1,2

--3.REVENUE BY CATEGORY

SELECT 
  I.ITEMCODE, 
  I.ITEMNAME, 
  I.CATEGORY1, 
  I.CATEGORY2,
  I.BRAND,
  SUM(OD.LINETOTAL) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.ITEMCODE, I.ITEMNAME, I.CATEGORY1, I.CATEGORY2,I.BRAND
ORDER BY 6 DESC

--4.AVERAGE MONTHLY REVENUE

SELECT 
  ROUND(AVG(TOTAL_PRICE),0) AS AVG_MONTHLY_REVENUE FROM
(
	SELECT 
  	YEAR(O.DATE_) AS ORDER_YEAR,
  	MONTH(O.DATE_) AS ORDER_MONTH,
  	SUM(O.TOTALPRICE) AS TOTAL_PRICE
	FROM ORDERS O
	GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
) AS MONTHLY_TOTALS

--5. REVENUE CONTRIBUTION % BY CATEGORY

SELECT 
    I.CATEGORY1 AS CATEGORY_NAME,
    SUM(OD.LINETOTAL) AS TOTAL_REVENUE,
    ROUND(SUM(OD.LINETOTAL) * 100.0 /
        (SELECT SUM(OD2.LINETOTAL) FROM ORDERDETAILS OD2),2) AS REVENUE_CON_PER_CATEGORY
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.CATEGORY1
ORDER BY 3 DESC

--6. REVENUE CONTRIBUTION % BY BRAND

SELECT 
    I.BRAND AS BRAND,
    SUM(OD.LINETOTAL) AS TOTAL_REVENUE,
    ROUND(SUM(OD.LINETOTAL) * 100.0 /
        (SELECT SUM(OD2.LINETOTAL) FROM ORDERDETAILS OD2),2) AS REVENUE_CON_PER_CATEGORY
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.BRAND
ORDER BY 3 DESC

--7.TOP PRODUCTS BY QUANTITIY

SELECT 
    I.CATEGORY1 AS CATEGORY_NAME,
    SUM(OD.AMOUNT) AS TOTAL_QUANTITY
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.CATEGORY1
ORDER BY 2 DESC

--8.TOP 10 PRODUCT BY QUANTITY: How many units were sold in total?

SELECT TOP 10
    I.ITEMNAME AS PRODUCT_NAME,
    COUNT(OD.AMOUNT) AS ORDER_FREQUENCY
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.ITEMNAME
ORDER BY 2 DESC

--9. MOST FREQUENTLY ORDERED PRODUCTS: In how many different orders did it appear?

SELECT TOP 10
    I.ITEMNAME AS PRODUCT_NAME,
    COUNT(DISTINCT OD.ORDERID) AS ORDER_FREQUENCY
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.ITEMNAME
ORDER BY 2 DESC


