--1.MONTHLY SALES TREND

SELECT 
  YEAR(O.DATE_) AS ORDER_YEAR,
  MONTH(O.DATE_) AS ORDER_MONTH,
  ROUND(SUM(O.TOTALPRICE),0) AS TOTAL_PRICE
FROM ORDERS O
GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
ORDER BY 1,2

--2.MONTHLY ORDER COUNT

SELECT 
  YEAR(O.DATE_) AS ORDER_YEAR,
  MONTH(O.DATE_) AS ORDER_MONTH,
  COUNT(DISTINCT O.ID) AS ORDER_COUNT
FROM ORDERS O
GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
ORDER BY 1,2

--3.REVENUE BY CATEGORY

SELECT 
  I.ITEMCODE, 
  I.ITEMNAME, 
  I.CATEGORY1, 
  I.CATEGORY2,
  I.BRAND,
  SUM(O.TOTALPRICE) AS TOTAL_REVENUE
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
JOIN ITEMS I ON I.ID = OD.ITEMID
GROUP BY I.ITEMCODE, I.ITEMNAME, I.CATEGORY1, I.CATEGORY2,I.BRAND
ORDER BY 6 DESC

--4.AVERAGE MONTHLY REVENUE

SELECT 
  ROUND(AVG(TOTAL_PRICE),0) AS AVG_MONTHLY_REVENUE FROM
(
	SELECT 
  	YEAR(O.DATE_) AS ORDER_YEAR,
  	MONTH(O.DATE_) AS ORDER_MONTH,
  	SUM(O.TOTALPRICE) AS TOTAL_PRICE
	FROM ORDERS O
	GROUP BY YEAR(O.DATE_) , MONTH(O.DATE_) 
) AS MONTHLY_TOTALS
